- name: Backup Cisco IOS running-config
  hosts: switches
  gather_facts: no

  tasks:
    - name: Save running config to a file
      ansible.netcommon.cli_command:
        command: show running-config
      register: running_config

    - name: Write running config to a local file
      copy:
        content: "{{ running_config.stdout }}"
        dest: "./backups/{{ inventory_hostname }}_running-config.txt"
